# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# echo 'Hello from .zshrc'

# Set Variables
## ZSH HOME (ZDOTDIR configures where dotfiles are stored for ZSH)
export ZSH=$HOME/.zsh
## History config
export SHELL_SESSIONS_DISABLE=1
export HISTFILE=$ZSH/.zsh_history
## How many commands zsh will load to memory
export HISTSIZE=10000
## How many commands history will save on file
export SAVEHIST=10000
## use Zsh's implementation instead of Apple's:
setopt SHARE_HISTORY
## History won't save duplicates
setopt HIST_IGNORE_ALL_DUPS
## History won't show duplicates on search
setopt HIST_FIND_NO_DUPS
## Automatically appends after every command
setopt INC_APPEND_HISTORY


export HOMEBREW_CASK_OPTS="--no-quarantine"
export NULLCMD=bat
export NVM_DIR="$HOME/.nvm"
  [ -s "$HOMEBREW_REPOSITORY/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_REPOSITORY/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "$HOMEBREW_REPOSITORY/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_REPOSITORY/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
export JAVA_HOME="$HOMEBREW_REPOSITORY/opt/openjdk/bin"

# Change ZSH Options

# Create Alisases (Use 'command' to bypass alias)
alias eza='eza -laFh --git'
alias ls='eza'
alias man='batman'
alias bbd='brew bundle dump --force --describe'
alias trail='<<<${(F)path}'
alias rm=trash


# Customize Prompt(s)
PROMPT='
%1~ %L %# '

# Timestamp to the right
RPROMPT='%*'

# Add Locations to $path Array
typeset -U path

path=(
  "$HOMEBREW_REPOSITORY/opt/openjdk/bin"
  $path
  # Add Visual Studio Code (code)
  "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
)

# Write Handy Functions
function mkcd() {
  mkdir -p "$@" && cd "$_";
}

## Automatically call nvm use (when entering a directory that has an .nvmrc file) ##
autoload -U add-zsh-hook

function load-nvmrc() {
  local nvmrc_path
  nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version
    nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$(nvm version)" ]; then
      nvm use
    fi
  elif [ -n "$(PWD=$OLDPWD nvm_find_nvmrc)" ] && [ "$(nvm version)" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}

add-zsh-hook chpwd load-nvmrc
load-nvmrc
## END nvmrc config ##

# Theme
source "$ZSH/themes/powerlevel10k/powerlevel10k.zsh-theme"
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Use ZSH Plugins
source "$ZSH/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$ZSH/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# ...and Other Surprises


